# Generated by Django 4.2.13 on 2025-05-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi_cam_stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='camera',
            table='Cameras',
        ),
        migrations.AlterModelTable(
            name='section',
            table='Sections',
        ),
        migrations.AlterModelTable(
            name='seracs',
            table='Seracs',
        ),
    ]
